return {
	favorites = { "kitty", "firefox" },
	skip_empty_icons = false,
  shape = Helpers.shape.rrect(Beautiful.medium_radius),
	placement = function(c)
		Helpers.placement(c, "bottom_left", nil, Beautiful.useless_gap * 3)
	end,
	border_color = Beautiful.widget_bg_alt,
	border_width = 0,
	background = Beautiful.widget_bg_color,
	icon_size = 48,
	apps_spacing = Dpi(6),
	default_app_icon_name = "default-application",
	app_show_icon = true,
	app_name_halign = "left",
	apps_per_row = 6,
	apps_per_column = 1,
	apps_margin = 0,
	-- app_height = Dpi(24),
	app_icon_width = Dpi(32),
	app_icon_height = Dpi(32),
	app_width = Dpi(260),
	app_shape = Helpers.shape.rrect(Beautiful.small_radius),
	app_content_padding = {
		left = Dpi(6),
		right = Dpi(6),
		bottom = Dpi(4),
		top = Dpi(4),
	},
	app_normal_color = Beautiful.widget_bg_color,
	app_normal_hover_color = Beautiful.widget_bg_alt,
	app_selected_color = Beautiful.widget_bg_alt,
	app_selected_hover_color = Helpers.color.ldColor(Beautiful.widget_bg_alt, 10, Beautiful.color_method),
	app_name_selected_color = Beautiful.accent_color,
	app_name_normal_color = Beautiful.foreground .. "6F",
	app_name_font = Beautiful.font_text .. "Regular 12",
	prompt_image_bg_ratio = 3,
	prompt_image_bg_height = Dpi(130),
	prompt_image_bg_shape = Helpers.shape.rrect(Beautiful.medium_radius),
	prompt_height = Dpi(40),
	prompt_margins = {
		right = Dpi(70),
		left = Dpi(70),
	},
	prompt_paddings = {
		left = Dpi(12),
		right = Dpi(10),
	},
	prompt_text = "",
	prompt_icon = "󰍉", -- 󰍉
	prompt_shape = Helpers.shape.rrect(Beautiful.small_radius),
	prompt_icon_font = Beautiful.font_icon .. "8",
	prompt_font = Beautiful.font_text .. "Regular 13",
	prompt_color = Beautiful.widget_bg_color,
	prompt_text_color = Beautiful.foreground .. "bb",
	prompt_icon_color = Beautiful.accent_color .. "DF",
	prompt_cursor_color = Beautiful.foreground .. "bb",
	grid_margins = Dpi(8),
	grid_spacing = Dpi(6),
}
