---@meta

--- @class ButtonNormal
--- @field protected _private table
--- @field color string Background color (hex)
--- @field halign string Horizontal alignment
--- @field valign string Vertical alignment
--- @field padding number Padding around the widget
-- --- @field normal_shape function Shape of the button in normal state
-- --- @field hover_shape function Shape of the button in hover state
-- --- @field press_shape function Shape of the button when pressed
--- @field normal_border_width number Border width in normal state
--- @field hover_border_width number Border width in hover state
--- @field press_border_width number Border width when pressed
--- @field normal_border_color string Border color in normal state
--- @field hover_border_color string Border color in hover state
--- @field press_border_color string Border color when pressed
--- @field on_hover function Function called when the mouse hovers over the button
--- @field on_leave function Function called when the mouse leaves the button
--- @field on_press function Function called when the button is pressed
--- @field on_release function Function called when the button is released
--- @field on_secondary_press function Function called on secondary mouse button press
--- @field on_secondary_release function Function called on secondary mouse button release
--- @field on_scroll_up function Function called on scroll up
--- @field on_scroll_down function Function called on scroll down
-- --- @field set_widget fun(self: ButtonNormal, widget: table) Sets the button children
--- @field get_widget fun():table table Gets the button widget children
-- --- @field set_color fun(self: ButtonNormal, color: string) Sets the button color
--- @field get_color fun():string Gets the button color
-- --- @field set_halign fun(self: ButtonNormal, halign: string) Sets the horizontal alignment
--- @field get_halign fun(self: ButtonNormal): string Gets the horizontal alignment
-- --- @field set_valign fun(self: ButtonNormal, valign: string) Sets the vertical alignment
--- @field get_valign fun(self: ButtonNormal): string Gets the vertical alignment
-- --- @field set_padding fun(self: ButtonNormal, padding: number) Sets the padding around the widget
--- @field get_padding fun(self: ButtonNormal): number Gets the padding around the widget
-- --- @field set_normal_shape fun(self: ButtonNormal, shape: function) Sets the shape of the button in normal state
--- @field get_normal_shape fun(self: ButtonNormal): function Gets the shape of the button in normal state
--- @field set_hover_shape fun(self: ButtonNormal, shape: function) Sets the shape of the button in hover state
--- @field get_hover_shape fun(self: ButtonNormal): function Gets the shape of the button in hover state
--- @field set_press_shape fun(self: ButtonNormal, shape: function) Sets the shape of the button when pressed
--- @field get_press_shape fun(self: ButtonNormal): function Gets the shape of the button when pressed
-- --- @field set_normal_border_width fun(self: ButtonNormal, width: number) Sets the border width in normal state
--- @field get_normal_border_width fun(self: ButtonNormal): number Gets the border width in normal state
--- @field set_hover_border_width fun(self: ButtonNormal, width: number) Sets the border width in hover state
--- @field get_hover_border_width fun(self: ButtonNormal): number Gets the border width in hover state
--- @field set_press_border_width fun(self: ButtonNormal, width: number) Sets the border width when pressed
--- @field get_press_border_width fun(self: ButtonNormal): number Gets the border width when pressed
-- --- @field set_normal_border_color fun(self: ButtonNormal, color: string) Sets the border color in normal state
--- @field get_normal_border_color fun(self: ButtonNormal): string Gets the border color in normal state
--- @field set_hover_border_color fun(self: ButtonNormal, color: string) Sets the border color in hover state
--- @field get_hover_border_color fun(self: ButtonNormal): string Gets the border color in hover state
--- @field set_press_border_color fun(self: ButtonNormal, color: string) Sets the border color when pressed
--- @field get_press_border_color fun(self: ButtonNormal): string Gets the border color when pressed
--- @field set_on_hover function(self: ButtonNormal, action: function) Sets the function to be called on hover
--- @field get_on_hover fun(self: ButtonNormal): function Gets the function to be called on hover
--- @field set_on_leave fun(self: ButtonNormal, action: function) Sets the function to be called on leave
--- @field get_on_leave fun(self: ButtonNormal): function Gets the function to be called on leave
--- @field set_on_press fun(self: ButtonNormal, action: function) Sets the function to be called on press
--- @field get_on_press fun(self: ButtonNormal): function Gets the function to be called on press
--- @field set_on_release fun(self: ButtonNormal, action: function) Sets the function to be called on release
--- @field get_on_release fun(self: ButtonNormal): function Gets the function to be called on release
--- @field set_on_secondary_press fun(self: ButtonNormal, action: function) Sets the function to be called on secondary press
--- @field get_on_secondary_press fun(self: ButtonNormal): function Gets the function to be called on secondary press
--- @field set_on_secondary_release fun(self: ButtonNormal, action: function) Sets the function to be called on secondary release
--- @field get_on_secondary_release fun(self: ButtonNormal): function Gets the function to be called on secondary release
--- @field set_on_scroll_up fun(self: ButtonNormal, action: function) Sets the function to be called on scroll up
--- @field get_on_scroll_up fun(self: ButtonNormal): function Gets the function to be called on scroll up
--- @field set_on_scroll_down fun(self: ButtonNormal, action: function) Sets the function to be called on scroll down
--- @field get_on_scroll_down fun(self: ButtonNormal): function Gets the function to be called on scroll down
local ButtonNormal = {}
-- --- Sets the button children
-- --- @param widget table the new widget 
-- function ButtonNormal:set_widget(widget) end


--- @class ButtonState: ButtonNormal
local ButtonState = {}