local theme_path = require("gears").filesystem.get_configuration_dir()
local schemes = {
  ["everblush"] = {
    wallpaper     = theme_path .. "/images/wallpapers/onedark_3.jpg",
    -- { COLORS }
    fg_normal     = "#d1d1d1",
    fg_alt        = "#282c34",
    bg_darker     = "#141a1c",
    bg_normal     = "#181f21",
    bg_alt        = "#20292b",
    bg_bright     = "#2a3538",
    -- { NORMAL }
    red           = "#e57474",
    green         = "#8ccf7e",
    yellow        = "#e5c76b",
    blue          = "#67b0e8",
    magenta       = "#c47fd5",
    cyan          = "#7bc7c7",
    gray          = "#c2c2c2",
    orange        = "#e6a06e",
    -- { LIGHT }
    red_light     = "#f07979",
    green_light   = "#91d682",
    yellow_light  = "#f0d070",
    blue_light    = "#6cb8f2",
    magenta_light = "#ce86e0",
    cyan_light    = "#70d4e0",
    gray_light    = "#dadada",
    orange_light  = "#f2a974",
  },
  ["gruvbox"] = {
    wallpaper     = theme_path .. "/images/wallpapers/gruvbox_2.png",
    -- { COLORS }
    fg_normal     = "#d4be98",
    fg_alt        = "#292828",
    bg_darker     = "#1F1F1F",
    bg_normal     = "#292828",
    bg_alt        = "#333232",
    bg_bright     = "#3D3C3C",
    -- { NORMAL }
    red           = "#ec6b64",
    green         = "#89b482",
    yellow        = "#F5B12C",
    blue          = "#6d8dad",
    magenta       = "#d3869b",
    cyan          = "#82b3a8",
    gray          = "#c7b89d",
    orange        = "#e78a4e",
    -- { LIGHT }
    red_light     = "#F77069",
    green_light   = "#92BF8A",
    yellow_light  = "#FFB82E",
    blue_light    = "#7496B8",
    magenta_light = "#DE8DA3",
    cyan_light    = "#89BDB1",
    gray_light    = "#D1C1A5",
    orange_light  = "#F29152",
  },
  ["onedark"] = {
    wallpaper     = theme_path .. "/images/wallpapers/onedark_3.jpg",
    -- { COLORS }
    fg_normal     = "#abb2bf",
    fg_alt        = "#282c34",
    bg_darker     = "#21252B",
    bg_normal     = "#282c34",
    bg_alt        = "#2f343d",
    bg_bright     = "#373D47",
    -- { NORMAL }
    red           = "#e06c75",
    green         = "#98c379",
    yellow        = "#e7c787",
    blue          = "#61afef",
    magenta       = "#C882E7",
    cyan          = "#56b6c2",
    gray          = "#abb2bf",
    orange        = "#DA8378",
    -- { LIGHT }
    red_light     = "#F57680",
    green_light   = "#A7D685",
    yellow_light  = "#FCD994",
    blue_light    = "#67BBFF",
    magenta_light = "#DB8EFC",
    cyan_light    = "#5FC9D6",
    gray_light    = "#c8ccd4",
    orange_light  = "#ED8F83",
  },
  ["cervos"] = {
    wallpaper     = theme_path .. "/images/wallpapers/cervos_3.png",
    -- { COLORS }
    fg_normal     = "#c8c8db",
    fg_alt        = "#171819",
    bg_darker     = "#111213",
    bg_normal     = "#171819",
    bg_alt        = "#1e2024",
    bg_bright     = "#27292e",
    -- { NORMAL }
    black         = "#2f3233",
    red           = "#dc7173",
    green         = "#78b892",
    yellow        = "#f4d392",
    blue          = "#759fe6",
    magenta       = "#ba93eb",
    cyan          = "#7cbdb3",
    gray          = "#a4a9b8",
    orange        = "#eba27f",
    -- { LIGHT }
    black_light   = "#393c3d",
    red_light     = "#e78284",
    green_light   = "#9bcc97",
    yellow_light  = "#edd6a4",
    blue_light    = "#8ab4f8",
    magenta_light = "#c6a0f6",
    cyan_light    = "#8ac8bf",
    gray_light    = "#b5b9c4",
    orange_light  = "#f5ab87",
    -- OTHER
  },
}
return schemes